name: CI

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 set_version.py
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Package Extension
        run: npm run package -- ./chrome-reddit-comment-arrow-${{ env.VERSION }}.zip
      - uses: actions/upload-artifact@v3
        with:
          name: chrome-reddit-comment-arrow-${{ env.VERSION }}
          path: ./chrome-reddit-comment-arrow-${{ env.VERSION }}.zip
      - name: Tag version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: "${{ secrets.PAT }}"
          custom_tag: ${{ env.VERSION }}
          tag_prefix: ""
