name: CI

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 set_version.py
      - uses: vimtor/action-zip@v1
        with:
          files: manifest.json content.js button.css popup.html popup.js images/ README.md LICENSE.md
          dest: ./chrome-reddit-comment-arrow-${{ env.VERSION }}.zip
          recursive: false
      - uses: actions/upload-artifact@v3
        with:
          name: chrome-reddit-comment-arrow-${{ env.VERSION }}
          path: ./chrome-reddit-comment-arrow-${{ env.VERSION }}.zip
      - name: Tag version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: "${{ secrets.PAT }}"
          custom_tag: ${{ env.VERSION }}
          tag_prefix: ""
