name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: chrome-reddit-comment-arrow-${{ env.VERSION }}
          path: ./chrome-reddit-comment-arrow-${{ env.VERSION }}.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ./chrome-reddit-comment-arrow-${{ env.VERSION }}.zip
